### ISSUE TITLE
Error Reporting only on Production?

### ISSUE THREAD

**Issue by christoph-werker** [TheoKouzelis/laravel-airbrake#21]
Hello Guys,

how can i report only online Errors in Production mode?

**Comment by TheoKouzelis** [comment]
It depends how you've implement the package into laravel. If you are using the log stacks, you can create different stack for each  environments. Then set which stack you want to use by changing the value of LOG_CHANNEL in .env https://laravel.com/docs/9.x/logging#introduction

Otherwise if you're using the exception handler, you can check the environment before sending the error to airbrake https://laravel.com/docs/9.x/configuration#determining-the-current-environment

**Comment by TheoKouzelis** [comment]
Exception handler example is now in the docs https://github.com/TheoKouzelis/laravel-airbrake/commit/02bdf9e7ef35959f7ec7974c7e3cd14eb10ed5c4

**Comment by christoph-werker** [comment]
Thanks
